### ISSUE TITLE
[WANT]ライセンスを明示してほしい

### ISSUE THREAD

**Issue by yakumo-saki** [mstdn-workers/wordcloud#16]
Wordcloudを自インスタンスで動かしたいのですが、
ライセンスが現状特に明示されていないので、もし可能であれば指定して頂けると助かります。

**Comment by vidolretia** [comment]
Wordcloudを自インスタンスで動かしたいのですが、
ライセンスが現状特に明示されていないので、もし可能であれば指定して頂けると助かります。

**Comment by called-d** [comment]
めちゃくちゃ放置しててごめんなさいね、とりあえずMITにしておきます。リポジトリにライセンスファイル置くのは後でやる

**Comment by yakumo-saki** [comment]
ありがとうございました。おかげで自インスタンスで動作できました。
